version: '2'
services:
  web:
    build: $PWD/deploy/php-apache/
    env_file: .env
    volumes:
     - $PWD/application:/var/www/html
     - $PWD/logs/apache:/var/log/apache2 
     - $PWD/deploy/php-apache/config/ssl:/etc/apache2/ssl
    ports:
        - "8888:80"
        - "8443:443"
    links:
      - mariadb:mysql
      - redis:redis
  mariadb:
    image: mariadb:10.1
    env_file: .env
    volumes:
      - $PWD/state/mariadb/mysql/:/var/lib/mysql
      - $PWD/temp/:/sqldata

  redis:
    env_file: .env
    image: redis:3.0.7
    ports:
        - "6379:6379"
