version: '2'
services:
  web:
    build: $PWD/deploy/php-apache/
    env_file: .env
    volumes:
     - $PWD/application/leedsinspired/htdocs:/var/www/html
     - $PWD/logs/apache:/var/log/apache2 
     - $PWD/deploy/php-apache/config/ssl:/etc/apache2/ssl
    ports:
        - "80:80"
        - "443:443"
    links:
      - mariadb:mysql
      - redis:redis
      - solr:solr
    networks:
      inspired:
        ipv4_address: 172.16.1.2
  mariadb:
    image: mariadb:10.1
    env_file: .env
    volumes:
      - $PWD/state/mariadb/mysql/:/var/lib/mysql
      - $PWD/temp/:/sqldata

    networks:
      inspired:
        ipv4_address: 172.16.1.3
 

  redis:
    env_file: .env
    image: redis:3.0.7
    ports:
        - "6379:6379"
    networks:
      inspired:
        ipv4_address: 172.16.1.4
 
  solr: 
    env_file: .env
    image: solr:6
    ports:
     - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    networks:
      inspired:
        ipv4_address: 172.16.1.5

volumes:
  solr:

networks:
  inspired:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
